version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:19.8.1
    working_directory: ~/app
    steps:
      - checkout
      - run: echo $MY_VAR
      - run: node --version
      - run: npm install

workflows:
  say-hello-workflow:
    jobs:
      - build
